# Generated by Django 2.0.3 on 2018-06-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commoName', models.CharField(max_length=32)),
                ('commoPrice', models.CharField(max_length=32)),
                ('commoInfo', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostName', models.CharField(max_length=32)),
                ('hostUrl', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='interfaceUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUrl', models.CharField(max_length=32)),
                ('addressUrl', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=32)),
            ],
        ),
    ]
