# Generated by Django 2.0.3 on 2018-06-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(null=True)),
                ('status', models.IntegerField(default=1, max_length=32)),
                ('create_time', models.DateTimeField(default=1528362509.5386164)),
                ('update_time', models.DateTimeField(default=1528362509.5386164)),
            ],
        ),
        migrations.CreateModel(
            name='hostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostName', models.CharField(max_length=32, null=True)),
                ('hostUrl', models.CharField(max_length=32, null=True)),
                ('status', models.IntegerField(default=1, max_length=32)),
                ('create_time', models.DateTimeField(default=1528362509.539113)),
                ('update_time', models.DateTimeField(default=1528362509.539113)),
            ],
        ),
        migrations.CreateModel(
            name='interfaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interfaceName', models.CharField(max_length=32, null=True)),
                ('interfaceUrl', models.CharField(max_length=32, null=True)),
                ('status', models.IntegerField(default=1, max_length=32)),
                ('create_time', models.DateTimeField(default=1528362509.5396085)),
                ('update_time', models.DateTimeField(default=1528362509.5396085)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, null=True)),
                ('userPhone', models.CharField(max_length=32, null=True)),
                ('userId', models.IntegerField(max_length=32, null=True)),
                ('status', models.IntegerField(default=1, max_length=32)),
                ('create_time', models.DateTimeField(default=1528362509.5366316)),
                ('update_time', models.DateTimeField(default=1528362509.5366316)),
            ],
        ),
        migrations.CreateModel(
            name='userFromId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(null=True)),
                ('userFromId', models.CharField(max_length=32, null=True)),
                ('status', models.IntegerField(default=1, max_length=32)),
                ('create_time', models.DateTimeField(default=1528362509.538118)),
                ('update_time', models.DateTimeField(default=1528362509.538118)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(max_length=32, null=True)),
                ('token', models.TextField(null=True)),
                ('openid', models.TextField(null=True)),
                ('create_time', models.DateTimeField(default=1528362509.5376227)),
                ('update_time', models.DateTimeField(default=1528362509.5376227)),
            ],
        ),
    ]
