# Generated by Django 2.0.3 on 2018-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.TextField(null=True),
        ),
    ]
