# Generated by Django 2.0.3 on 2018-06-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='create_time',
            field=models.DateTimeField(default=1528369167.7960846),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='update_time',
            field=models.DateTimeField(default=1528369167.7960846),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='create_time',
            field=models.DateTimeField(default=1528369167.796578),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='update_time',
            field=models.DateTimeField(default=1528369167.796578),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='create_time',
            field=models.DateTimeField(default=1528369167.797074),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='update_time',
            field=models.DateTimeField(default=1528369167.797074),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=1528369167.7945917),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(default=1528369167.7945917),
        ),
        migrations.AlterField(
            model_name='userfromid',
            name='create_time',
            field=models.DateTimeField(default=1528369167.7955859),
        ),
        migrations.AlterField(
            model_name='userfromid',
            name='update_time',
            field=models.DateTimeField(default=1528369167.7955859),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(default=1528369167.7950902),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='update_time',
            field=models.DateTimeField(default=1528369167.7950902),
        ),
    ]
