# Generated by Django 2.0.3 on 2018-07-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceinfo',
            name='resData',
            field=models.TextField(null=True),
        ),
    ]
