# Generated by Django 2.0.3 on 2018-06-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180612_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='hostName',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='hostUrl',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='interfaceName',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='interfaceUrl',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='methodType',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPhone',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userfromid',
            name='userFromId',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
