# Generated by Django 2.0.3 on 2018-08-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_interfaceinfo_resdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCanvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvasImg', models.ImageField(max_length=256, upload_to='canvas/img')),
                ('canvasid', models.CharField(max_length=256, null=True)),
                ('create_time', models.IntegerField(null=True)),
            ],
        ),
    ]
