# Generated by Django 2.0.3 on 2018-08-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180803_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercanvas',
            name='userid',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='usercanvas',
            name='canvasImg',
            field=models.ImageField(max_length=256, upload_to='canvas/img'),
        ),
    ]
