# Generated by Django 2.0.3 on 2018-08-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180803_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='baseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercanvas',
            name='userid',
        ),
        migrations.AddField(
            model_name='usercanvas',
            name='answer',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='usercanvas',
            name='moblie',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='usercanvas',
            name='canvasImg',
            field=models.ImageField(max_length=256, upload_to='canvas/img'),
        ),
    ]
