# Generated by Django 2.0.3 on 2018-08-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180803_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercanvas',
            name='canvasImg',
            field=models.ImageField(max_length=256, upload_to='static/img'),
        ),
    ]
